### ISSUE TITLE
Task log response does not conform to specs

### ISSUE THREAD

**Issue by uniqueg** [EMBL-EBI-TSI/TESK#107]
### Problem description

Accessing `GET /v1/tasks/{id}` via `py-tes v0.3.0` yields the following error:

```console
UnmarshalError: {'logs': [{'start_time': '2020-05-07T18:50:27.000Z', 'end_time': '2020-05-07T18:50:31.000Z', 'exit_code': 0}], 'metadata': {'GROUP_NAME': 'ELIXIR-CH', 'USER_ID': 'some_user_name'}, 'start_time': '2020-05-07T18:49:58.000Z', 'end_time': '2020-05-07T18:50:43.000Z', 'system_logs': [None]} could not be unmarshalled to type: ExecutorLog
```

### Expected outcome

The call should return the task log.

### Probable cause

It appears that the response does not conform to the `ExecutorLog` model defined by `py-tes v0.3.0` in the [`models.py`](https://github.com/ohsu-comp-bio/py-tes/blob/712801eefddc87d958af73ff58ecdb5ba981873e/tes/models.py) module as:

```py
@attrs
class ExecutorLog(Base):
    start_time = attrib(
        default=None,
        convert=timestampconv,
        validator=optional(instance_of(datetime))
    )
    end_time = attrib(
        default=None,
        convert=timestampconv,
        validator=optional(instance_of(datetime))
    )
    stdout = attrib(
        default=None, convert=strconv, validator=optional(instance_of(str))
    )
    stderr = attrib(
        default=None, convert=strconv, validator=optional(instance_of(str))
    )
    exit_code = attrib(
        default=None, validator=optional(instance_of(int))
    )
```

This model is identical to [the one used](https://github.com/ohsu-comp-bio/py-tes/blob/752be687793fd0806240222b538f94e4df7dfd6f/tes/models.py) in the latest version of `py-tes` (0.4.0) is in line with the [current version of the TES specs](https://github.com/ga4gh/task-execution-schemas/blob/9cc12b0c215a7f54fdeb0d0598ebc74fa70eb2a7/openapi/task_execution.swagger.yaml), which defines the `ExecutorLog` model as:

```yaml
  tesExecutorLog:
    type: object
    properties:
      start_time:
        type: string
        description: 'Time the executor started, in RFC 3339 format.'
      end_time:
        type: string
        description: 'Time the executor ended, in RFC 3339 format.'
      stdout:
        type: string
        description: |-
          Stdout content.
          This is meant for convenience. No guarantees are made about the content.
          Implementations may chose different approaches: only the head, only the tail,
          a URL reference only, etc.
          In order to capture the full stdout users should set Executor.stdout
          to a container file path, and use Task.outputs to upload that file
          to permanent storage.
      stderr:
        type: string
        description: |-
          Stderr content.
          This is meant for convenience. No guarantees are made about the content.
          Implementations may chose different approaches: only the head, only the tail,
          a URL reference only, etc.
          In order to capture the full stderr users should set Executor.stderr
          to a container file path, and use Task.outputs to upload that file
          to permanent storage.
      exit_code:
        type: integer
        format: int32
        description: Exit code.
    description: ExecutorLog describes logging information related to an Executor.
    required: 
    - exit_code
    readOnly: true
```

Instead, TESK returns the following JSON object:

```json
{
    "logs" : [ {
        "start_time" : "2020-05-07T18:50:27.000Z",
        "end_time" : "2020-05-07T18:50:31.000Z",
        "exit_code" : 0
    } ],
    "metadata" : {
        "GROUP_NAME" : "ELIXIR-CH",
        "USER_ID" : "some_user_name"
    },
    "start_time" : "2020-05-07T18:49:58.000Z",
    "end_time" : "2020-05-07T18:50:43.000Z",
    "system_logs" : [ null ]
}
```

### Steps to reproduce

Install `py-tes 0.3.0` with:

```bash
pip install py-tes==0.3.0
```

Then in a Python instance execute:

```py
import tes

task_id = "VALID_TASK_ID"  # add here ID of task that you have access to

tes_client = tes.HTTPClient(
    url="https://csc-tesk.c03.k8s-popup.csc.fi"
)

task_log = tes_client.get_task(
    task_id=task_id,
    view="FULL",
)
```
